name: Python CI/CD Pipeline

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: | 
          pytest --junitxml=test-results/result.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-results/results.xml

